### ISSUE TITLE
[BUG]Dictionaries are completely drilled down

### ISSUE THREAD

**Issue by rmestrum** [docsible/docsible#100]
## Describe the Bug

When you you have a dictionary or array in a variable file alle the dictionary elements are treated like they are variables until the value has a primitive value like a string
When the value is a non primitive, like an hash or array it should only that is a hash or array instead of the real value.

This makes understanding the variable and its default value difficult because you need to construct it yourselfs again from the readme. 

## Environment

- **Docsible Version**: 0.7.24
- **Python Version**: [e.g., 3.13.3]
- **Operating System**: macOS]
- **CLI or Script**: CLI

## To Reproduce

Describe the steps to reproduce the behavior:

1. Create the following yaml
```
---
my-var1-key1-reference:
  sub-key11: sub-key11-value
  sub-key12: sub-key12-value

my-var1-key2-reference:
  sub-key21: sub-key11-value
  sub-key22: sub-key12-value

my-var1-key3-reference:
  sub-key31: sub-key31-value
  sub-key32: sub-key32-value

my-var1:
  key1: >-
    {{ my-var1-key1-reference }}
  key2: >-
    {{ my-var1-key2-reference }}
  key3: >-
    {{ my-var1-key3-reference }}
```
2. Execute 
    docsible --role <rolename> -o test.md -nob

## Expected Behavior

The variable overview in the readme should be like this or similar to this
```
| Var          | Type         | Value       |
|--------------|--------------|-------------|
| [my-var1-key1-reference](defaults/main/main.yml#L258)   | dict | <pre>sub-key11: sub-key11-value<br/>sub-key12: sub-key12-value</pr> |
| [my-var1-key2-reference](defaults/main/main.yml#L262)   | dict | <pre>sub-key21: sub-key11-value<br/>sub-key22: sub-key12-value</pre>` |
| [my-var1-key3-reference](defaults/main/main.yml#L266)   | dict | <pre>sub-key31: sub-key31-value<br/>sub-key32: sub-key32-value</pre> |
`sub-key32-value` |
| [my-var1](defaults/main/main.yml#L270)   | dict | <pre>key1: >-<br/>  {{ my-var1-key1-reference }}<br/>key2: >-<br/>  {{ my-var1-key2-reference }}<br/>key3: >-<br/>  {{ my-var1-key3-reference }}</pre> |
```

You now see the original value that configured for the variables.

## Actual Behavior

The actual behavior is

```

| Var          | Type         | Value       |
|--------------|--------------|-------------|
| [my-var1-key1-reference](defaults/main/main.yml#L258)   | dict | `{}` |    
| [my-var1-key1-reference.**sub-key11**](defaults/main/main.yml#L259)   | str | `sub-key11-value` |    
| [my-var1-key1-reference.**sub-key12**](defaults/main/main.yml#L260)   | str | `sub-key12-value` |    
| [my-var1-key2-reference](defaults/main/main.yml#L262)   | dict | `{}` |    
| [my-var1-key2-reference.**sub-key21**](defaults/main/main.yml#L263)   | str | `sub-key11-value` |    
| [my-var1-key2-reference.**sub-key22**](defaults/main/main.yml#L264)   | str | `sub-key12-value` |    
| [my-var1-key3-reference](defaults/main/main.yml#L266)   | dict | `{}` |    
| [my-var1-key3-reference.**sub-key31**](defaults/main/main.yml#L267)   | str | `sub-key31-value` |    
| [my-var1-key3-reference.**sub-key32**](defaults/main/main.yml#L268)   | str | `sub-key32-value` |    
| [my-var1](defaults/main/main.yml#L270)   | dict | `{}` |    
| [my-var1.**key1**](defaults/main/main.yml#L271)   | str | `<multiline value: folded_strip>` |    
| [my-var1.**key2**](defaults/main/main.yml#L273)   | str | `<multiline value: folded_strip>` |    
| [my-var1.**key3**](defaults/main/main.yml#L275)   | str | `<multiline value: folded_strip>` |    
```

## Logs

If applicable, add logs to help explain your problem.

## Additional Context

Add any other context about the problem here, such as relevant system information or peculiarities in your setup.

## Python Console Output

If you can, please also include the console output when running the CLI or script.

```
[console output here]
```
