### ISSUE TITLE
[BUG] Mermaid graph not displaying for include task

### ISSUE THREAD

**Issue by cdp181** [docsible/docsible#35]
## Describe the Bug

When running against a role with an include task the mermaid graph on github.com is not rendered and gives the following error (removing the braces allows the graph to render) :

```
Unable to render rich display
Parse error on line 12:
...ask| testlogin_yml0[{{import test login}
-----------------------^
Expecting 'TAGEND', 'STR', 'MD_STR', 'UNICODE_TEXT', 'TEXT', 'TAGSTART', got 'DIAMOND_START'

For more information, see https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
flowchart TD
Start
classDef block stroke:#3498db,stroke-width:2px;
classDef task stroke:#4b76bb,stroke-width:2px;
classDef includeTasks stroke:#16a085,stroke-width:2px;
classDef importTasks stroke:#34495e,stroke-width:2px;
classDef includeRole stroke:#2980b9,stroke-width:2px;
classDef importRole stroke:#699ba7,stroke-width:2px;
classDef includeVars stroke:#8e44ad,stroke-width:2px;
classDef rescue stroke:#665352,stroke-width:2px;

  Start-->|Include task| testlogin_yml0[{{import test login}}<br>include_task: {{testlogin yml}}]:::includeTasks
  testlogin_yml0-->|Include role| platform_role_loader1(include platform role loader<br>include_role: platform role loader):::includeRole
  platform_role_loader1-->End

```

## Environment

- **Docsible Version**: 0.7.2
- **Python Version**: 3.13
- **Operating System**: Linux
- **CLI or Script**: CLI

## To Reproduce

Describe the steps to reproduce the behavior:

Running docsible against a role which contains an Include Task :

```
---
- name: import test login
  ansible.builtin.include_tasks: testlogin.yml

- name: Include platform_role_loader
  ansible.builtin.include_role:
    name: platform_role_loader
  vars:
    platform_role_loader_name: tacacs
```
