### ISSUE TITLE
[BUG] Unusual order of Ansible task parameters doesn't work

### ISSUE THREAD

**Issue by NikodimMatvienko** [docsible/docsible#37]
## Describe the Bug

Utility doesn't correctly handle unusual order of Ansible task parameters.

## Environment

- **Docsible Version**: 0.7.3
- **Python Version**: 3.11
- **Operating System**: Linux
- **CLI or Script**: CLI

## To Reproduce

Describe the steps to reproduce the behavior:

1. Create task within testin role with unusual order of parameters like:
```yaml
   - name: Test
     when: ansible_facts['distribution_major_version'] == '9'
     ansible.builtin.command:
       cmd: test
 ```

2. Run the docsible command:
`docsible --role .`

3. In generated README it will be represented like:
#### File: tasks/test.yml

| Name | Module | Has Conditions |
| ---- | ------ | --------- |
| Test | when | False |

## Expected Behavior

It should be:

#### File: tasks/test.yml

| Name | Module | Has Conditions |
| ---- | ------ | --------- |
| Test | ansible.builtin.command | False |

## Actual Behavior

Instead of generating the module name, it incorrectly puts the `when` parameter. The same issue occurs for any other parameters that are placed in a different order.
