### ISSUE TITLE
[BUG] Graph is always added for playbook when --playbook option used

### ISSUE THREAD

**Issue by jmcook1** [docsible/docsible#47]
## Describe the Bug
When generating README.md for a role and included a playbook example, the graph is always generated.

## Environment

- **Docsible Version**: 0.7.8
- **Python Version**: 3.9.19
- **Operating System**: Linux (RHEL 9)
- **CLI or Script**: CLI

## To Reproduce

Describe the steps to reproduce the behavior:
Run `docsible --role ../ansible_collections/snhu/ansible_windows/roles/sql_server_cluster --playbook sql_server_cluster.yml` 
(any role & playbook should reproduce the problem)

## Expected Behavior
Just the playbook section is included in README.md

## Actual Behavior
Both the playbook and the mermaid diagram are included:

  ## Playbook
  ```yml
  ---
  - name: Configure SQL Server Cluster
    hosts: all
    gather_facts: false
    vars_files:
      - "vars/{{ ad_domain }}_ad_info.yml"
    vars:
      sql_server_mgrs: "SQLManagers"
      sql_cno: test_cno
      sql_vco: test_vco
      sql_ou: "OU=SQL Servers,OU=Servers,DC=my,DC=com"
      sql_dc: "{{ ad_dc }}"

    tasks:
      - name: Create SQL Server Cluster in "{{ sql_dc }}"
        ansible.builtin.import_role:
          name: snhu.ansible_windows.sql_server_cluster

  ```
  ## Playbook graph
  ```mermaid
  flowchart TD
    all-->|Import role| snhu_ansible_windows_sql_server_cluster0([create sql server cluster in  sql dc <br>import_role: snhu ansible 
  windows sql server cluster]):::importRole
  ```
