### ISSUE TITLE
[BUG] Repetitive ansible.builtin.include_tasks breaks mermaid

### ISSUE THREAD

**Issue by gni** [docsible/docsible#76]
## Describe the Bug

Repetitive `ansible.builtin.include_tasks` breaks mermaid

## Environment

docsible, version 0.7.19

## To Reproduce

```yaml
- name: Collect hardware metrics
  block:
    # Collect CPU usage
    - name: Collect CPU usage
      ansible.builtin.include_tasks: collect_metric.yml
      vars:
        metric_name: "CPU usage"
        metric_command: "top -bn1 | grep 'Cpu(s)' | awk '{print 100 - $8}'"
        metric_register: "cpu_usage"
        metric_collect: sysinspect_collect_hardware

    # Collect memory usage
    - name: Collect memory usage
      ansible.builtin.include_tasks: collect_metric.yml
      vars:
        metric_name: "Memory usage"
        metric_command: "free | awk '/Mem/ {printf(\"%.2f\", $3/$2 * 100.0) }'"
        metric_register: "mem_usage"
        metric_collect: sysinspect_collect_hardware

    # Collect disk usage
    - name: Collect disk usage
      ansible.builtin.include_tasks: collect_metric.yml
      vars:
        metric_name: "Disk usage"
        metric_command: "df / --output=pcent | tail -1 | tr -dc '0-9'"
        metric_register: "disk_usage"
        metric_collect: sysinspect_collect_hardware
```

## Expected Behavior

A nice mermaid graph..

## Actual Behavior
 
Unreadable graph
