### ISSUE TITLE
Issue with comment handling in tasks file when generating README

### ISSUE THREAD

**Issue by gni** [docsible/docsible#82]
**Description**:
When generating the README using `docsible`, the comments in the `tasks.yml` file are not handled correctly. Specifically, extra comments (like block names) are being added to the README that are not intended to be part of the documentation.

For example, in the following task file:

```yaml
#SPDX-License-Identifier: MIT-0
---
# tasks file for loopmatic

# --- User Login Check Block ---
- name: User login check block
  block:
    - name: Vérifier la connexion SSH
      ansible.builtin.ping:
      register: result_ping
      failed_when: result_ping.ping != "pong"
      changed_when: false
      tags: [ssh_check]

    - name: Vérifier la dernière connexion de l'utilisateur spécifique
      ansible.builtin.shell: |
        set -o pipefail
        lastlog -u {{ loopmatic_user_name }} | head -n 1
      register: last_login
      failed_when: last_login.stdout == ""
      changed_when: false
      tags: [login_check]

  rescue:
    - name: Handle errors in user login block
      ansible.builtin.debug:
        msg: "⚠️ Failed to check user login."
```

The README generated includes additional comments, such as:

```yaml
# tasks file for loopmatic
```

However, only the block name should appear in the generated README, like so:

```yaml
# --- User Login Check Block ---
- name: User login check block
  block:
    ...
```

**Expected Behavior**:
The README should only include block titles (e.g., `# --- User Login Check Block ---`) and should not include other task comments or unnecessary details from the tasks in the YAML file.

**Steps to Reproduce**:

1. Create a `tasks.yml` file with comments like 
```yaml
# tasks file for loopmatic
# --- User Login Check Block ----
```
2. Run `docsible` to generate the README.
3. Observe that the comments are incorrectly included in the generated README.
