### ISSUE TITLE
[BUG] comments fail when using double quoted task names

### ISSUE THREAD

**Issue by marszip** [docsible/docsible#91]
## Describe the Bug

When running the cli command with the —comments option, no comments are being generated in the READM.md file.  It seems to be caused by the use of double quotes in the resource names.  

## Environment

- **Docsible Version**: 0.7.22
- **Python Version**: 3.13.3
- **Operating System**: macOS
- **CLI or Script**: CLI

## To Reproduce

This example works fine:

```
# tasks/main.yml
---
# Install web server package
- name: Install nginx
  package:
    name: nginx
    state: present
```

And this one fails to generate comments:

```
# tasks/main.yml
---
# Install web server package
- name: "Install nginx"
  package:
    name: "nginx"
    state: "present"
```

## Expected Behavior

I would expect the same behavior in both cases. 

## Actual Behavior

No comments and no logging

## Logs

Not available
